<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- 1 -->
    <script>
        const promise = new Promise((resolve, reject) => {
            console.log(1)
            resolve()
            console.log(2)
        })
        promise.then(() => {
            console.log(3)
        })
        console.log(4)
    </script>
    <!-- 2 -->
    <script>
        const promise1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('success')
            }, 1000)
        })
        const promise2 = promise1.then(() => {
            throw new Error('error!!!')
        })

        console.log('promise1', promise1)
        console.log('promise2', promise2)

        setTimeout(() => {
            console.log('promise1', promise1)
            console.log('promise2', promise2)
        }, 2000)
    </script>
    <!-- 3 -->
    <script>
        const promise3 = new Promise((resolve, reject) => {
            resolve('success1')
            reject('error')
            resolve('success2')
        })
        promise3
            .then((res) => {
                console.log('then: ', res)
            })
            .catch((err) => {
                console.log('catch: ', err)
            })
    </script>
    <!-- 4 -->
    <script>
        Promise.resolve(1)
            .then((res) => {
                console.log(res)
                return 2
            })
            .catch((err) => {
                return 3
            })
            .then((res) => {
                console.log(res)
            })
    </script>
    <!-- 5 -->
    <script>
        const promise5 = new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log('once')
                resolve('success')
            }, 1000)
        })

        const start = Date.now()
        promise.then((res) => {
            console.log(res, Date.now() - start)
        })
        promise.then((res) => {
            console.log(res, Date.now() - start)
        })
    </script>
    <!-- 6 -->
    <script>
        Promise.resolve()
            .then(() => {
                return new Error('error!!!')
            })
            .then((res) => {
                console.log('then: ', res)
            })
            .catch((err) => {
                console.log('catch: ', err)
            })
    </script>
    <!-- 7 -->
    <script>
        const promise7 = Promise.resolve()
            .then(() => {
                return promise
            })
        promise.catch(console.error)
    </script>
    <!-- 8 -->
    <script>
        Promise.resolve(1)
            .then(2)
            .then(Promise.resolve(3))
            .then(console.log)
    </script>
    <!-- 9 -->
    <script>
        Promise.resolve()
            .then(function success(res) {
                throw new Error('error')
            }, function fail1(e) {
                console.error('fail1: ', e)
            })
            .catch(function fail2(e) {
                console.error('fail2: ', e)
            })
    </script>
    <!-- 10 -->
    <script>
        process.nextTick(() => {
            console.log('nextTick')
        })
        Promise.resolve()
            .then(() => {
                console.log('then')
            })
        setImmediate(() => {
            console.log('setImmediate')
        })
        console.log('end')
    </script>
</body>

</html>